### ISSUE TITLE
System.IO.FileNotFoundException has been thrown while setting up the package

### ISSUE THREAD

**Issue by parthrparekh93** [Pkcs11Interop/Pkcs11Interop.X509Store#12]
I am using .NET core 3.1 on Mac and installed Pkcs11Interop.X509Store 0.2.0 version to read attached smart card certificates. 

```
string pkcs11LibraryPath = @"/Library/OpenSC/lib/opensc-pkcs11.so";
using (var store = new Pkcs11X509Store(pkcs11LibraryPath, new SimplePinProvider("000000")))
{
}
```

I get the following exception

Could not load file or assembly 'Pkcs11Interop, Version=4.0.0.0, Culture=neutral, PublicKeyToken=c10e9c2d8c006d2a'. The system cannot find the file specified

I have not installed Pkcs11Interop package but even if I do, I get the same error.

**Comment by jariq** [comment]
`Pkcs11Interop.X509Store` uses `Pkcs11Interop` as a dependency and cannot work without it.

Try installing `Pkcs11Interop.X509Store` from [nuget.org](https://www.nuget.org/packages/Pkcs11Interop.X509Store/). `Pkcs11Interop` will be installed automatically as a dependency.

**Comment by parthrparekh93** [comment]
Installing Pkcs11Interop.X509Store does not install Pkcs11Interop package on Visual studio for Mac so I had to manually install Pkcs11Interop version 4.0.0. Even after doing that, I get the same error message.

**Comment by jariq** [comment]
@parthrparekh93 have you managed to resolve this issue?

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
