### ISSUE TITLE
Does X509Store is only in read-only session?

### ISSUE THREAD

**Issue by Dvergatal** [Pkcs11Interop/Pkcs11Interop.X509Store#25]
Hi Guys,
i was recently thinking about using this library in my project to remove openssl dependency, but from what i have read in the code, the store's session is only in read-only state. Correct me if i'm wrong.

**Comment by jariq** [comment]
That's correct. `Pkcs11Interop.X509Store` library works with existing certificate and key objects in a read-only mode. If you also need to create new objects you can use `Pkcs11Interop` library directly.

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
