### ISSUE TITLE
FindKey includes label

### ISSUE THREAD

**Issue by DadOfTheDead** [Pkcs11Interop/Pkcs11Interop.X509Store#26]
Hi, 
on my card private key and public key of the certificate are not found. I dug into it and found that your search for keys in `FindKeys` in `Pkcs11X509Certificate` includes `CKA_ID` and also `CKA_Label`. On my card however Label is only set on the certificate - not on either of the keys - when importing the certificate using the provider tool (Thales SafeNet). Do you think it is a good idea to exclude label search not only for me but everyone?
BR and thanks for your work.

Edit: Tested with another type of card (ACOS). When putting a certificate on that card label is not set for either certificate, private key or public key. All empty.

**Comment by jariq** [comment]
Yes, excluding `CKA_LABEL` from search template sounds like a good idea. I'll remove it in next version.

**Comment by DadOfTheDead** [comment]
Thanks

**Comment by jariq** [comment]
This feature will be published today in Pkcs11Interop.X509Store 0.4.0.
