### ISSUE TITLE
Using ECDSA with SignedXML

### ISSUE THREAD

**Issue by zosocanuck** [Pkcs11Interop/Pkcs11Interop.X509Store#27]
Hi,

I'm getting the following error when attempting to sign XML with an ECDSA keypair:

```
Unhandled exception. System.Security.Cryptography.CryptographicException: Failed to create signing key.
   at System.Security.Cryptography.Xml.SignedXml.ComputeSignature()
```

Any ideas?

**Comment by jariq** [comment]
After taking a look at the [reference source](https://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/signedxml.cs,365) of `System.Security.Cryptography.Xml.SignedXml` class I would say it currently supports only `RSA` and `DSA` algorithms. However quick [DuckDuckGo](https://duckduckgo.com) search pointed me to blogpost [ECDSA and Custom XML Signatures in .NET](https://www.scottbrady91.com/c-sharp/ecdsa-xml-dotnet) that may help you.

**Comment by jariq** [comment]
You might also take a look at https://github.com/dotnet/runtime/issues/36103

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
