### ISSUE TITLE
TLS ?

### ISSUE THREAD

**Issue by fliot** [Pkcs11Interop/Pkcs11Interop.X509Store#40]
Is there a way to use this X509Store for a TLS communication and to handle an HSM /PKCS11 based mutual TLS communication ?

**Comment by jariq** [comment]
https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/blob/1.0.0/doc/05_FAQ.md#can-i-use-a-certificate-from-pkcs11interopx509store-for-ssl-connections

**Comment by fliot** [comment]
Thansk @jariq 
I understand default .NET platform specific TLS options make it impossible.
Do you know some C# pure implementation which enable HSM/PKCS11 based mutual TLS communication ? Even with lower performance, but exclusively in C# ?

**Comment by jariq** [comment]
AFAIK [Bouncy Castle](https://github.com/bcgit/bc-csharp) implements TLS stack in pure C#. It won't support PKCS#11 out of the box but it should be possible to extend it.
